version: "3.9"
services:
  tg-postgres:
    image: postgres:14.5
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
