version: "3.9"
services:
  postgres:
    image: postgres:14.5
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - ../data/postgres/:/var/lib/postgresql/data/

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ../docker-compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../docker-compose/prometheus/alerts.yml:/etc/prometheus/alerts.yml
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana:
    image: grafana/grafana-oss
    ports:
      - '3000:3000'
    volumes:
      - ../data/grafana/:/var/lib/grafana
    links:
      - prometheus
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.18
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686' # web
      - '14268:14268'
      - '9411:9411'

  redis:
    image: redis:6.2
    restart: unless-stopped
    volumes:
      - ../data/redis/data:/data
    ports:
      - '6378:6379'

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - '9092:9092'
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "example-topic:2:1"
    depends_on:
      - zookeeper